apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: eurotransit-cluster
servers: 1
agents: 2                                       #worker nodes to test PodDisruptionBudget and topologySpreadConstraints of Pillar C
image: rancher/k3s:v1.28.2-k3s1 
ports:
  - port: 8080:80                               #maps port 80 from the cluster to 8080 locally to avoid conflicts with system ports
    nodeFilters:
      - loadbalancer
  - port: 8443:443        
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik                   #CRITICAL: disables the native Traefik for now, than will install the specific (required) version
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true