---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: eurotransit-notifications-smtp
  namespace: eurotransit
spec:
  encryptedData:
    SPRING_MAIL_PASSWORD: AgB2CwTNJCxi2eSR98s4LhLZ0kp+Xn/OM9MgP7pZDDz1TUyWzl4PS2z5kojwRxzLqoi081q7WGCuHkaOFLEuu0T4csL3v72h1jpQEUbu4sbhPPLr3G1+swof1qZGLN173/xUuBOtquj/07IJwMa7GJE6OnDJfzH/vqRQ+0sCLsqmEB6BdOmvqa8g4gSNl/m1OHUi2CJ+xpKvjRpjW+tMgSYhRb2zfa6f6r0Lo1PPqtDs/9Dq2qOY52DfS9IZNaol+5yBGLvlQwTV7OuilTwMnzBx9byeQfU52gDjUFTFd+VpQZ3jLa6IY/fZ48Lmc9I8sc1q2XqWqWf9FX5PzYSwI8mWtsVscXW/zym2QrhmCJGCFsJduDhEgi3jIH2NeuEuAHZj7Y+sFXGbpzBCa2KeBz/R53u5ND8Z4Lbk/0NSzQBrr5viQtUPBOFSgd4Z+l2e9yAF5CMsoM6xE4SzWeUNbpmurHK3wNCQKMYbOP1xQAMCTR7K85OjM3/oZrIMORSNafzr2TlMwwxzXU8pxsCY5BJGeL3IFuN+KuAjpmNtth8d2CxFGYA5hwiU/E1++AqX3t7vCJrbaAcwnvAIJyiVW7uuKP14pLXPe9lBwLbf9EsClhsYGbtm21Emrsbce0DnDrvlamMh++SIS5WRg/znfLo+i6iDafzgANrwrs2NQmT9qgCY+9euUAr148DgAcf1t77CEIwr38jye3AHrWFIwA==
    SPRING_MAIL_USERNAME: AgBGw1vL4Y+6ljSVnfP4beM4bCSd2dlqdI0iv8XHxVvECfK6RoUuXYGxij4ktPKtLT0iYkq2EY3lmEI/DxlpNMUu/uz6gS698q4Q0P8qsxJrNuU94GTDbhD0TiFMKg4NEDNHgzgfU34gECp/HXqVEdZspWVGNMzUNiqRWyiRJiQ0pzaIWMplNvDnf1NICllQxW1xD+6dY4xtg0VRyf9naEiuuj0305rgF7MJSEHFQ2kcBllGnZR7uy9D0guwVlnsUpvaHwgCmCnV+s/Xjk33Yt7EdK4XP0KOeiNqfpwwZo2Rr3ylMa6xHGcVfc1mlFmqBEV1sRhMAkERVnChDYX++p7XRhMqX3Jk84vxHdf7t0T4EcXSE15W8VGCH0Pq2FvjbSPgKCFQhSoMWc1k4Z5mr8npQNYwZ2g1dpygfZsU8ijaMfFson++w3Dht81jrb7yV9TFYd9BC1ggn1eRmpYqM1QsGno56GlyzfjKW/08IIJZrJ/x7cRtIKDhJ0Bcw5x2pqpxwte7aN28wFtjSl1wiYY9zEQsRbNYSFypDEmxZH3CCYFCeyfhf2UP6DsburUGiZcHb5fXqGvypvIfs3pVlRynZFiZKdb/SLT6E01XVLI3xEdw3/7PzoAz4zV/n9yzeMdLE7dpw9/7cx7rYn44qBGA/KbFMa56ujFfCy10gKfndqEIy98pb2ui2OY07osKfWd45nU9R98FM15uphVk/A==
  template:
    metadata:
      name: eurotransit-notifications-smtp
      namespace: eurotransit
