apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: eurotransit-inventory
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: eurotransit-inventory
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "eurotransit.commonLabels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: eurotransit-inventory
      app.kubernetes.io/instance: {{ .Release.Name }}
