---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAsADBmapfSSPmRPguuGpag+1hle1dRFR2Gd51JDlnx3ayZlIVmlI2FEtyZW0psAw2d8sB7H40eFH7zOyCshk/ijBZ40WBM+jKaeDPcqhDs4uEqTPu5B3txPLrXZz3krBu9NcJjSB1qQ1FVc3Ly3LFqnLdxjUvF8nTiNtWi/cL81yqGJ6obxzu+a3itpyKgAStkTFXLahXI7dwYY7m3JWUIcyGRg7RTC5i+FeFidA8J/nQEJHuy0+bQ1LoV9VeZMEKxx15a/lZEGww0wzOQTS9ZOJ1PS7QxGi661URW/huraKXBT/IspFX/0sANhqJEffc6a8gT2fsCGnbUsYBDUAt/QZo72dTvlG2ZL7yENFC0HOkGmjy9VMizYK67RjsdaqWBe7/JNCi7VCWy3daIketr+7hMF/2Zhv+rrCKVtrGx+hLu8IgXW/QyaDMnQY8ObcYr9qcCOotwPvmAtF6FEpPOyBga85qBDx+BJbuhWlRSd2c8kPBpRJaz+OEruLhe6DaPJvfJT/fTpr6wEdEUs9BaTMQtiXchaUZTMS677oXOIochqvFz4VEVA8bnRFaaYjrsRAHKfDwrI4idJk4uSfs0bn3ebsjPrLChBzbtAezuOe+3+4VmhCujHV7Gc94hpo0BAW9AObP5VJPW3MJV3hZxuCQ5yGS40FGnYO5zJe1TxyWvMEN7umHCqIhHV8rIbfEda7u9WILJ+tG2c5p7D7tjHazNuPRJilU=
    admin-user: AgBDtdIYSGpQ91lGWGTE+P0NI5m3TUMBH4RQzCngc8osxYLRObw8ZzRdWbahs/SVjGM5XavB+hE0QAtj6ciVQRL/9B37lmfdY0JcDmwYs3Brmj3PvA1LUO33tnI+WXAJe9wlSiJJU7JSsJ4gfA1SPuX4QEpD3GK6DluSode5SVLITqdX6mBoVWXS/VBPPLXTQ5FMlY0aEpmTqePIOv4jnSQjZUm/AOppNW/6FSVpDaD6zoiCoagLfP0hlf1nCqaJIducrCSOOGpFGFq6uowCMLR3VULBIUcgJ9IokYu9SW+24wTwSrdjjiA9u5GTjR8soNS0DIdY4HI867MG6DdMoG59EtoiaTqEm0GjNDFBYXPSc9eQclCbyONSZhOnsVxOwjes5zZPXIR0ETHoPO4UEkAb3keP+afqE8spJpmgTsBepcRbvIXtDVMS9vW8GIYQbsEYnJDKB7V9lv7TiHtwTVPaNT5k5XNX3Ggx8IfhIzIVndflEyMYFi+CZwmKPKZVH1am7e1e8jdXRMYz9amgfueLbGlEj0evEUhsQQtLNO6MXALgYgyyKOI2ZkEhn6kKUOped5hmfTBGIOg43fDwkkwgb8AQnGQtY8/bTleQx1GI0soynKETKiftZNvnJjWQAJ1hWmAeyYpF2Y7uwoUEzC94s4o9DZ0pTVaIuPeJE55FUIo7y9t/KWLBRtKECQSziLic20jrFg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
