---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-github-oauth
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GITHUB_CLIENT_ID: AgA8MaqxYe043y3yMazN/kdv0FVunuUn8bs8Yv8gp3wAQQEdbUB0CQ+F9TAeCT8Zl3LJUnW91GBY4v0NA7tRX9eUfsij33s3OiWvF2us6fGWCCwPFwgVGPGWgU42tvV8p9kFj7ZAVzP9P/XoNLT8x2vazKhpHdEiicIthLGOjh7xzyqGSYd1U1rJDepcb1z3b+YMxvBFSkZsTnrPv29lLCBX0Jrx3pHe0bN+6H7l67YsOnH6Ck0w4b1xhCLdD2iLo7T0+1QArNwBHn/KxvRHnVMjZsnP36H40C9Wa7O1qtsqtPMDOInsCMqp/5YqQp7XmO/iYchcXgNAvUgHUzxWfP0ZRltR+8/n8hIF8gSrXvWSKiXgkWjAfvBh35/Zl0H7uHP1yJjyLAE8AcknEKeAJ3CTOu4GYp4Y58qcpZ7l5HCdGEluOwqvO8oSdySF0uZv/YD3QvtQkEdW8AImS4U0l6b/n3nqOW/6gHyvjjEooqrn/rcVhGNEoIZuuX7y7oD6b4E8oNa467VpQhbHzXql6Dk5xtsXB2LkI4gelhngvF+yeCIMXV1uJLCsJeNSPxN3qRirTIohCqT+cenyosS/is7rM+lLcUixSgTwwvJZC02May6TDqobzGFH/bOE7tKJpzOUcLqQu1B6L4TC/3qwi30FqXscQgdUz8gWCj66/wP7MYLsyp0saUbewLYsNclduEaZmEEmrfUkXqIS83/8Evp+88To+w==
    GF_AUTH_GITHUB_CLIENT_SECRET: AgCNWfrxQW0ehO1pAGlf0TBYgKe1eo8dnMZH7LZNhXmCOn+jiJtTWONo9y+zqQzI/FMtq4axacAGxFKLChVKA79SO3BmyOnfGOKJU272Igi23/eJNKJetv74/ZT55dWtsrWYq2aYQe+ZrvDLmkxrDvxeKH3flFVH46hoGdpmqdpEvuBxKJl0emhBP9KhpaGpdZSR9aSD4g88xJ1shr0kJ4EgxGXYeo63KiDTD+tvNfToEcLBCvGSNQffIdfZecAc/aeVzL5ZgmC6qvr+uvfu/nXO8mZeYcmYmSxLl0GyfByuxoNEO0/vQi+rQRu89SMulx85aINzQLEaiWQpJAcUGPn4GTyf9KSjmwolOiNGwaVily1WbZIfOBk2tzGS5BgctVwRhwzSSF71Hw1F4PADj9nZb2+ygho7ZROXfllhf5wBN5ECpQoK0N40pSyH3n8wQGzQMiSUlVeJU2gsO7zyCS1sCj3R5YmvqZP4d4+7XL82BiS542bk4lH8ui71qLTFnR2N/KXKvw+gD7Z5kTAhhcA2r+iqS5AarbKVDe9+gGdy42hytu/SEbX9ZV+iYSmXyXok73VgQbqsGiXJEpy3aag6BzS1bGgXK7Lo5uIYGMZmwGIjImcmCtV0vgYUJpRSBoA8tIEuicu6s3HSIxlNIGXtfX76SDh1zsBMxnBDw3TN4Lr9Zf5KZnpg4zTdHr02p1p7OrH4V1PI1RhTS+Hobski7JRr42zSEHk5cFcmWG/PKirmb+DnCqnp
  template:
    metadata:
      name: grafana-github-oauth
      namespace: monitoring
    type: Opaque
