---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-github-oauth
  namespace: argocd
spec:
  encryptedData:
    clientID: AgBrkzXb8PfWzq4vU4U1Dz3Kh2/d8+uyKA5UuoRQxw/UaDNxIGl2HFbQaauVg7L25aZTysT5ikxr4yUWUmwiPmrKich90FDTkEyR08YiIvCSL32HpHuPFQIPiScbOWjV+wQfJVW8mEucnHnowEsPtEEyveG4+uAmlwRsGgOAUIDhTTJAj3zYwEDH3uL71dRdFk4brN0n9U8tflHX/K9kZCLL+xZLo/EBHOhbfzCUj8x2lj6kO4abftx8+z3Z1sTF+mTx9EoHGcPWN5B2m6+HkLZPDXBp3mlrbUSMhHv6dGD48hw8timuLDzZA/OwbOs83eRmjgPR52lfEIzKeWPDSCvehbjTVgU/3ztGmmr1pAQSrkn6rPeXP9SXzuyVvQzHVU4trpa0Ch9s2xCfo2ArDM2+zrySQ4ZAL3qYqqRjJrjn/PObY2lLfIlQsrJ7q8KeBq6c/bBSh54fKrZ2+TbTvnYk4RWjFfYmoy/7Gmohs7Soop1sbzZuW2z16wn6rnTDt3TNM1z+cHPJd7u7RcUoC82cKuupatKj+nuXMP8j+p6f4wkAIVOA5n73sC17Uik0Cler/gJLAGIUofe0ODzfOhbmTG58tDl5ZR2lVLWfqprMw+Otxr0FaGHLsdnsA0R0LaROaXJZNaEnMR18oghK0oBb/imUtcoVH9emp4RK4HruWEIfcrUvvsCKIsdwEmpFjkduiZ82JbwYZrKu0/j85UDIgIx79w==
    clientSecret: AgAuuzjmxdB/uzYRY8uRTdK7/lPHYON8314cZ8J/eC9Q9gRyJcXXKbrfBqcQERs2qDmxON1BBYjvYv1BdDXQIlx3Upt0pHZQPnrNYyNKF4xAG+VfOIMF53QCsAyFWWG6Il+3zaqRWz6Ut/xNz9iIxAHVm00lzan79LwwkJgkDQQHSEYgdc+edHP93qxC96AinkNOePiRV5vqEl5/bK1jeQ7zXhs2LgMf4SESghDni75A5VNl38VbrgCqFJuUdbO4ys2ViDjJfs8vtDOh0jS6Dc+lQUWw53RdVw24Wqget3LuZcdNvc3Vp222MQ5Z7y4acw3YL0+2Z4p15LrkQ0q+ZJQRfroiI0HMF8EPem63Ch4ixszgie1AmyMwT3GtYSc1L8/t7CKqYq8y18buqcY23afgK5LMG39TDv65MKxgv/M6zWkkv56f13q4FvpnfLsGsu9+2RjeOXBno3WFOaemEU89pwpJmIhKIk9KoW7RC2GHv0x7Kr9vNlRU+lCY1R27yDTktZt0uGARd/Z332SXbGXgETQ5kk4h6WRrjrR22+j3QYdnbsX4cc+5o7CFfzwAl06X6/1K1Vxz6Q1tpwA1RhJC5gk4liPyZrXPdnEEOdi6l3cGxRjlFV/1V9uhrKmWtDspt8w3v3rUPcrwzALHxSErLE3tMUmTnC6/DGudqLNaTfUumjMpb09vMnUGlckn6/HKeb8PG5kuGXdOSOZ2AEnY0NQ2wyLOJW0bAntPzy8wz38KQn6miEBF
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-github-oauth
      namespace: argocd
    type: Opaque
