---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    webhook.github.secret: AgCfDc8KvIOyZDpI/1EgjGtQnM9Gl5e5OHCOJwPUbBbpCZEPB33+gd3xyGKUQR+7jPb/8hEKWijwHgC2Wu5iKkkzNsOaAZ46xtt2Sauj69cOsFxv8vUQyF8Q7cTlqQNXPlq5VyU1K13AvONwiOJezyy0PwT2TXlrVziXsmTpW+qxb95RZ7H1YCJ8YVWU7JbhX/15Oi5NINPaCAW7V9XdjwZzPfULacFzVro110YjKQRNxIb786XIVd5Zy9Gvy9BywgIp4KF14GMJV1d0swNpXJo6CqjoZldO6vWvJqUgAuOw1SiZTsX1T97ZFUcWqD5SXbzYyV5aLXcADBxpX2BZ7R2FmYfi7PhFSPdH1EI7uwAj+xR6WiPLRFmeXmXG8PpSkKA3qowtW+C5t7M4NxUFJ4Dv2EEBsf0QIKbpt9qsLsAmddBm4Npdq8Ji+sNUaUP+SF6MgnMAUnzaVS2aF9NyQZU8V4OGUih1w0x3+W/aYA463b6ci+IPV63w8XarOy8VJdgmfnV0zLhwCsO25l4z10/37ZNuCSupPDpVFTw4zRkH163nf9ZEqOjvErngnLFmOLgkHQCuE17P4+YGoliyrYh65ayAAPnqpvmblEMg9oSc41GKMraJJsUOTRh8kdj9syu5kEWBL1M3gEF4YWBPWlg4xGiJ8pWZ6eoLoTNC1ZACTRty5gxE1H/hgk436sd9brMtLlZuOijWpDETTZHrRdBFreBSm3EFss2HFjU6usPK7LqlL3dA22nQ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
        sealedsecrets.bitnami.com/patch: "true"
        sealedsecrets.bitnami.com/skip-set-owner-references: "true"
      name: argocd-secret
      namespace: argocd
