apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eurotransit-payments
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: eurotransit-payments
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "eurotransit.commonLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eurotransit-payments
  minReplicas: {{ .Values.payments.hpa.minReplicas }}
  maxReplicas: {{ .Values.payments.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.payments.hpa.targetCPUUtilizationPercentage }}
