apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: order-placed
  namespace: eurotransit
  labels:
    strimzi.io/cluster: eurotransit-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: inventory-reserved
  namespace: eurotransit
  labels:
    strimzi.io/cluster: eurotransit-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: payment-authorized
  namespace: eurotransit
  labels:
    strimzi.io/cluster: eurotransit-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: order-confirmed
  namespace: eurotransit
  labels:
    strimzi.io/cluster: eurotransit-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: notification-requested
  namespace: eurotransit
  labels:
    strimzi.io/cluster: eurotransit-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000