apiVersion: v1
kind: Service
metadata:
  name: eurotransit-orders
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: eurotransit-orders
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "eurotransit.commonLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: eurotransit-orders
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
